### ISSUE TITLE
Code coverage is broken on recent Xcodes

### ISSUE THREAD

**Issue by ofalvai** [bitrise-steplib/steps-xcode-test#182]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? latest
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The step has an input `generate_code_coverage_files`, which seems to enable code coverage generation for xcodebuild.

If this input is set the Step appends `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES` and `GCC_GENERATE_TEST_COVERAGE_FILES=YES` args to the `xcodebuild` command.

Setting these args was the way prior to Xcode 7 so that the test result bundle does not contain code coverage information.

Code coverage prior Xcode 7:  https://mgrebenets.github.io/mobile%20ci/2015/02/08/code-coverage-for-ios

From Xcode 7 `-enableCodeCoverage YES` needs to be used instead.

Coverage data can be obtained from the result bundle this way:  https://developer.apple.com/forums/thread/124329

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

```yaml
    - xcode-test:
        inputs:
        ...
        - generate_code_coverage_files: "yes"
    - script:
        inputs:
        - content: |-
            #!/bin/env bash
            set -ex
            # line coverage percentages for each target, source file, and function/method that has coverage information
            xcrun xccov view --report $BITRISE_XCRESULT_PATH

            # get the list of files from result bundle
            xcrun xccov view --archive --file-list  $BITRISE_XCRESULT_PATH

            # get line coverage for a given file
            xcrun xccov view --archive --file "$BITRISE_SOURCE_DIR/_tmp/ios-simple-objc/ios-simple-objc/ViewController.m" $BITRISE_XCRESULT_PATH
```

Actual result:
xccov throws an error: `Error: Error Domain=XCCovErrorDomain Code=0 "No coverage data in result bundle" UserInfo={NSLocalizedDescription=No coverage data in result bundle}`
