### ISSUE TITLE
Bitrise reports test suite as passing, despite failures, when using `retry_on_failure`

### ISSUE THREAD

**Issue by jessesquires** [bitrise-steplib/steps-xcode-test#195]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? [Latest, 4.x](https://github.com/bitrise-steplib/steps-xcode-test/releases/tag/4.0.0)
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

Seems slightly related to #187, although that describes a different issue.

### Issue description

When using `test_repetition_mode: "retry_on_failure"`, if there are actual test failures, Bitrise reports that all tests have succeeded and the step does not fail.

```yaml
- xcode-test:
  title: Unit Tests
  inputs:
  - project_path: "$WORKSPACE"
  - scheme: "$SCHEME_UNIT"
  - destination: "$DEST_IPAD"
  - test_repetition_mode: "retry_on_failure"
  - maximum_test_repetitions: 3
```

### Bitrise info

- Build URL:
    - With `retry_on_failure` enabled, passes (incorrect): https://app.bitrise.io/build/f046cabd-5961-4807-90b1-d2a5b93c590c#?tab=log
    - With `retry_on_failure` **disabled**, fails (correct): https://app.bitrise.io/build/41e9bbcb-9af0-45f5-8a64-b8682589771e#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Logs: attaching screenshots below 

These are the test results with `retry_on_failure` **enabled** (i.e., the configuration above). As you can see, they are incorrectly reported as "succeeded" even though there are failures.

```yaml
- xcode-test:
  title: Unit Tests
  inputs:
  - project_path: "$WORKSPACE"
  - scheme: "$SCHEME_UNIT"
  - destination: "$DEST_IPAD"
  # RETRY ON FAILURE
  - test_repetition_mode: "retry_on_failure"
  - maximum_test_repetitions: 3
```

<img width="924" alt="Screen Shot 2021-10-20 at 1 57 02 PM" src="https://user-images.githubusercontent.com/2301114/138171061-60f09357-12f0-43b4-95be-f1a69c1e55bc.png">

These are the test results **without** specifying `test_repetition_mode` and `maximum_test_repetitions`. As you can see, the failure is correctly reported.

```yaml
- xcode-test:
  title: Unit Tests
  inputs:
  - project_path: "$WORKSPACE"
  - scheme: "$SCHEME_UNIT"
  - destination: "$DEST_IPAD"
  # DO NOT RETRY
```

<img width="939" alt="Screen Shot 2021-10-20 at 1 57 41 PM" src="https://user-images.githubusercontent.com/2301114/138171106-10d5e2ba-8deb-4a9a-90a5-e6dfed0ce9fa.png">

### Steps to reproduce

1. Create an Xcode project with unit tests
2. Write tests that fail
3. Add the following to your `xcode-test` step:
```yaml
  - test_repetition_mode: "retry_on_failure"
  - maximum_test_repetitions: 3
```
4. `xcode-test` reports that test succeeded, despite having failures.
5. Remove `test_repetition_mode` and `maximum_test_repetitions`
6. Tests now report as failed.
